spring:
  data:
    mongodb:
      uri: >-
        mongodb+srv://root:root@practicemongo.u4ybetk.mongodb.net/?retryWrites=true&w=majority&appName=PracticeMongo
      database: LibraryManagement
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka/'
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true


